-- Run this once in Supabase Dashboard > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '', last_name text not null default '',
  email text not null, phone text, role text not null default 'student' check (role in ('student','tutor','admin')),
  email_verified boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.courses (id text primary key, code text not null, title text not null, field text not null, level text, created_at timestamptz not null default now());
create table if not exists public.universities (id bigint generated by default as identity primary key, name text not null, country text, unique(name,country));
create table if not exists public.tutors (
  id text primary key, user_id uuid references public.profiles(id) on delete set null,
  name text not null, course text not null, school text not null, rating numeric(2,1) default 0,
  reviews integer default 0, price numeric(10,2) not null, image text, mode text not null,
  modes text[] not null default '{}', available text, published boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.favorites (user_id uuid references public.profiles(id) on delete cascade, tutor_id text references public.tutors(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,tutor_id));
create table if not exists public.catalog_requests (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, type text not null, name text not null, university text, country text, status text not null default 'pending_review', created_at timestamptz not null default now());
create table if not exists public.tutor_requests (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, subject text not null, university text, level text, location text, mode text not null, language text default 'English', budget numeric(10,2), details text not null, status text not null default 'open', created_at timestamptz not null default now());
create table if not exists public.resources (id uuid primary key default gen_random_uuid(), uploader_id uuid references public.profiles(id) on delete set null, course_id text references public.courses(id) on delete set null, title text not null, type text, url text not null, original_name text, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.tutor_applications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade, application jsonb not null default '{}', gpa numeric(3,2) not null, status text not null default 'pending', created_at timestamptz not null default now());
alter table public.tutor_applications alter column gpa drop not null;
alter table public.tutor_applications add column if not exists review_stage text not null default 'initial_screening';
alter table public.tutor_applications add column if not exists reviewer_id uuid references public.profiles(id) on delete set null;
alter table public.tutor_applications add column if not exists reviewer_notes text;
alter table public.tutor_applications add column if not exists decision_reason text;
alter table public.tutor_applications add column if not exists reviewed_at timestamptz;
create table if not exists public.sessions (id uuid primary key default gen_random_uuid(), owner_id uuid references public.profiles(id) on delete cascade, details jsonb not null default '{}', status text not null default 'draft', created_at timestamptz not null default now());
create table if not exists public.bookings (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade, details jsonb not null default '{}', price numeric(10,2) not null, people integer not null default 1, payment_account text, payment_status text not null default 'awaiting_verification', payment_reference text, payment_proof text, tutor_payout numeric(10,2), platform_share numeric(10,2), status text not null default 'pending', payout_status text, confirmed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.login_notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade, event_key text not null unique, provider text, sent_at timestamptz, created_at timestamptz not null default now());

-- Automatically create a profile after email or OAuth signup.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, first_name, last_name, email, phone, email_verified)
  values (new.id, coalesce(nullif(new.raw_user_meta_data->>'first_name',''), nullif(split_part(coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name',''), ' ', 1),''), 'Student'), coalesce(new.raw_user_meta_data->>'last_name',''), coalesce(new.email,''), new.raw_user_meta_data->>'phone', new.email_confirmed_at is not null)
  on conflict (id) do update set email=excluded.email, email_verified=excluded.email_verified;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email_confirmed_at on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security; alter table public.courses enable row level security;
alter table public.universities enable row level security; alter table public.tutors enable row level security;
alter table public.favorites enable row level security; alter table public.catalog_requests enable row level security;
alter table public.tutor_requests enable row level security; alter table public.resources enable row level security;
alter table public.tutor_applications enable row level security; alter table public.sessions enable row level security;
alter table public.bookings enable row level security;
alter table public.login_notifications enable row level security;

drop policy if exists "public courses" on public.courses;
create policy "public courses" on public.courses for select using (true);
drop policy if exists "public universities" on public.universities;
create policy "public universities" on public.universities for select using (true);
drop policy if exists "published tutors" on public.tutors;
create policy "published tutors" on public.tutors for select using (published);
drop policy if exists "published resources" on public.resources;
create policy "published resources" on public.resources for select using (status='approved');
drop policy if exists "published sessions" on public.sessions;
create policy "published sessions" on public.sessions for select using (status='published');
drop policy if exists "own profile" on public.profiles;
create policy "own profile" on public.profiles for select using (auth.uid()=id);
drop policy if exists "update own profile" on public.profiles;
create policy "update own profile" on public.profiles for update using (auth.uid()=id);
drop policy if exists "own favorites" on public.favorites;
create policy "own favorites" on public.favorites for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own tutor requests" on public.tutor_requests;
create policy "own tutor requests" on public.tutor_requests for select using (auth.uid()=user_id);
drop policy if exists "own applications" on public.tutor_applications;
create policy "own applications" on public.tutor_applications for select using (auth.uid()=user_id);
drop policy if exists "submit own application" on public.tutor_applications;
create policy "submit own application" on public.tutor_applications for insert with check (auth.uid()=user_id and status='submitted');
drop policy if exists "own bookings" on public.bookings;
create policy "own bookings" on public.bookings for select using (auth.uid()=user_id);

insert into storage.buckets (id,name,public,file_size_limit) values ('resources','resources',true,10485760) on conflict (id) do nothing;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('tutor-verification','tutor-verification',false,10485760,array['application/pdf','image/jpeg','image/png']) on conflict (id) do update set public=false,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "upload own tutor evidence" on storage.objects;
create policy "upload own tutor evidence" on storage.objects for insert to authenticated with check (bucket_id='tutor-verification' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "read own tutor evidence" on storage.objects;
create policy "read own tutor evidence" on storage.objects for select to authenticated using (bucket_id='tutor-verification' and (storage.foldername(name))[1]=auth.uid()::text);

insert into public.courses(id,code,title,field,level) values
('math-calculus-1','MATH 101','Calculus I','Mathematics','100'),('chem-organic','CHEM 204','Organic Chemistry','Physical Sciences','200'),
('cs-data-structures','CS 214','Data Structures','Computer Science','200'),('law-contract','LAW 206','Contract Law','Law','200')
on conflict (id) do nothing;
insert into public.tutors(id,name,course,school,rating,reviews,price,image,mode,modes,available,published) values
('ama','Ama Serwaa','Calculus II','University of Ghana',4.9,48,45,'/assets/tutor1.jpg','Online & in person',array['online','in-person'],'Available today',true),
('kwame','Kwame Mensah','Digital Signal Processing','KNUST',4.8,36,50,'/assets/tutor2.jpg','Online',array['online'],'Next slot 4:00 PM',true),
('nana','Nana Adjei','Organic Chemistry','University of Ghana',5.0,29,55,'/assets/tutoring1.jpg','Online & in person',array['online','in-person'],'Available today',true)
on conflict (id) do update set price=excluded.price, available=excluded.available;
